#include "Add_Header.h"

///////////////    И Н И Ц И А Л И З А Ц И Я     ////////////////////// 
														
////////////// В Х О Д ////////////////////
		
 void inputsInit(void)
 {
	  RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	  RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	  RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	
	 CLEAR_BIT(GPIOB->MODER, GPIO_MODER_MODER1_0 | GPIO_MODER_MODER1_1 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER2_1 |
	 GPIO_MODER_MODER14_0 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER4_1 |
	 GPIO_MODER_MODER5_0 | GPIO_MODER_MODER5_1 | GPIO_MODER_MODER10_0 | GPIO_MODER_MODER10_1); // сброс битов нулевого и первого в регистре MODER ЗНАЧИТ, что пины PA2,PA3,PB3,PB4,PB5,PB10 настроены на input , на этих пинах будут кнопки
											
	 MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR5_0 | GPIO_PUPDR_PUPDR10_0 | GPIO_PUPDR_PUPDR14_0 | GPIO_PUPDR_PUPDR4_0,
	 GPIO_PUPDR_PUPDR1_1 | GPIO_PUPDR_PUPDR2_1 |	GPIO_PUPDR_PUPDR5_1 | GPIO_PUPDR_PUPDR10_1 | GPIO_PUPDR_PUPDR14_1 | GPIO_PUPDR_PUPDR4_1 );  //установка пина в состоянии PULL_DOWN, тоесть на пине будет 0. комбинация PUPDR -10(первый бит один- нулевой бит ноль) 
	
////////// Кнопка USER Batton на плате Nucleo ////////////////
	 
	 CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODER13_0 | GPIO_MODER_MODER13_1); 
         MODIFY_REG(GPIOC->PUPDR, GPIO_PUPDR_PUPDR13_1, GPIO_PUPDR_PUPDR13_0);
	 GPIOC->BSRR |= GPIO_BSRR_BS13;
 }
 ////////////// В Ы Х О Д ////////////////////
 
 void outputsInit(void)
 {
	 //// L E D   N U C L E O  P A 5////
	 
	 MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER5_1, GPIO_MODER_MODER5_0); 
	 
	//// L E D  O N  T H E  B O A R D ////
	 
	 MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 , GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0); //01 - GP OUTPUT MODE
	 SET_BIT(GPIOB->BSRR, GPIO_BSRR_BS_8 | GPIO_BSRR_BS_9);
	 CLEAR_BIT(GPIOB->OTYPER, GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9); //0 - PUSH PULL 
	 MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR9_1, GPIO_OSPEEDER_OSPEEDR8_0 | GPIO_OSPEEDER_OSPEEDR9_0); //MED SPEED
	 MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPDR8_1 | GPIO_PUPDR_PUPDR9_1, GPIO_PUPDR_PUPDR8_0 | GPIO_PUPDR_PUPDR9_0); //pull_UPP - 01, подтяжка к 1
	 
 }
